function(__begin_minpack_builder_customize_dialog_wxs)
    set(__target_dir "${WIXTOOLSET_PROJECT_DIR}")

    file(MAKE_DIRECTORY ${__target_dir})

    set(__target_file "${__target_dir}/${WIXTOOLSET_PROJECT_MINPACK_BUILDER_CUSTOMIZE_DIALOG_FILE_NAME}")

    if (EXISTS ${__target_file})
        file(REMOVE ${__target_file})
    endif()

    file_append_line(${__target_file} "<?xml version=\"1.0\" encoding=\"utf-8\" ?>")
    file_append_line(${__target_file} "<Wix xmlns=\"http://wixtoolset.org/schemas/v4/wxs\">")
endfunction()

function(__append_lines_on_minpack_builder_customize_dialog_wxs lines)
    set(__target_dir "${WIXTOOLSET_PROJECT_DIR}")
    set(__target_file "${__target_dir}/${WIXTOOLSET_PROJECT_MINPACK_BUILDER_CUSTOMIZE_DIALOG_FILE_NAME}")

    if (NOT EXISTS ${__target_file})
        message(FATAL_ERROR "File \"${__target_file}\" not found")
    endif()

    foreach(line_content "${lines}")
        file_append_line(${__target_file} "${line_content}")
    endforeach()
endfunction()

function(__append_indented_lines_on_minpack_builder_customize_dialog_wxs indent_level lines)
    get_tabs_indentation("${indent_level}" content_indentation)
    foreach (line_content ${lines})
        __append_lines_on_minpack_builder_customize_dialog_wxs("${content_indentation}${line_content}")
    endforeach()
endfunction()

function(__append_blank_line_on_minpack_builder_customize_dialog_wxs indent_level)
    get_tabs_indentation("${indent_level}" content_indentation)
    __append_lines_on_minpack_builder_customize_dialog_wxs("${content_indentation}")
endfunction()

function(__append_comment_on_minpack_builder_customize_dialog_wxs indent_level comment_value)
    get_tabs_indentation("${indent_level}" content_indentation)
    __append_lines_on_minpack_builder_customize_dialog_wxs("${content_indentation}<!-- ${comment_value} -->")
endfunction()

function(__end_minpack_builder_customize_dialog_wxs)
    __append_lines_on_minpack_builder_customize_dialog_wxs("</Wix>")
endfunction()

function(write_minpack_builder_customize_dialog_wxs compiler_ids)
    __begin_minpack_builder_customize_dialog_wxs()
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(1)
    __append_comment_on_minpack_builder_customize_dialog_wxs(1 "Load project definitions")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(1 "<?include ${WIXTOOLSET_PROJECT_INCLUDE_FILE_NAME}?>")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(1)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(1 "<Fragment>")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(2 "<UI>")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(3 "<Dialog Id=\"MinpackBuilderCustomizeDialog\" Width=\"370\" Height=\"270\" Title=\"!(loc.CustomizeDlg_Title)\" TrackDiskSpace=\"yes\">")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Tree\" Type=\"RadioButtonGroup\" X=\"25\" Y=\"85\" Width=\"270\" Height=\"115\" Property=\"\$(ActiveCompilerChoiceProperty)\">")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<RadioButtonGroup Property=\"\$(ActiveCompilerChoiceProperty)\">")
    set(_radio_button_y "5")
    foreach(compiler_id ${compiler_ids})
        __append_indented_lines_on_minpack_builder_customize_dialog_wxs(6 "<RadioButton X=\"15\" Y=\"${_radio_button_y}\" Width=\"250\" Height=\"20\" Value=\"\$(${compiler_id}ChoicePropertyDefaultValue)\" Text=\"\$(${compiler_id}DisplayText)\"/>")
        MATH(EXPR _radio_button_y "${_radio_button_y} + 20")
    endforeach()
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "</RadioButtonGroup>")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "</Control>")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Back\" Type=\"PushButton\" X=\"192\" Y=\"243\" Width=\"56\" Height=\"17\" Text=\"!(loc.WixUIBack)\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Next\" Type=\"PushButton\" X=\"248\" Y=\"243\" Width=\"56\" Height=\"17\" Default=\"yes\" Text=\"!(loc.WixUINext)\">")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<Publish Event=\"AddLocal\" Value=\"ALL\"/>")
    foreach(compiler_id ${compiler_ids})
        __append_blank_line_on_minpack_builder_customize_dialog_wxs(5)
        __append_comment_on_minpack_builder_customize_dialog_wxs(5 "Remove features of the compiler ${compiler_id}")
        __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<Publish Event=\"Remove\" Value=\"${compiler_id}ChoiceOnReg\" Condition=\"\$(ActiveCompilerChoiceProperty)&lt\;&gt\;&quot\;\$(${compiler_id}ChoicePropertyDefaultValue)&quot\;\"/>")
        __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<Publish Event=\"Remove\" Value=\"${compiler_id}EnvVars\" Condition=\"\$(ActiveCompilerChoiceProperty)&lt\;&gt\;&quot\;\$(${compiler_id}ChoicePropertyDefaultValue)&quot\;\"/>")
        __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<Publish Event=\"Remove\" Value=\"${compiler_id}InstalledCompilers\" Condition=\"\$(ActiveCompilerChoiceProperty)&lt\;&gt\;&quot\;\$(${compiler_id}ChoicePropertyDefaultValue)&quot\;\"/>")
    endforeach()
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "</Control>")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Cancel\" Type=\"PushButton\" X=\"304\" Y=\"243\" Width=\"56\" Height=\"17\" Cancel=\"yes\" Text=\"!(loc.WixUICancel)\">")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(5 "<Publish Event=\"SpawnDialog\" Value=\"CancelDlg\" />")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "</Control>")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"BannerBitmap\" Type=\"Bitmap\" X=\"0\" Y=\"0\" Width=\"370\" Height=\"44\" TabSkip=\"no\" Text=\"!(loc.CustomizeDlgBannerBitmap)\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Text\" Type=\"Text\" X=\"25\" Y=\"55\" Width=\"320\" Height=\"20\" Text=\"!(loc.CustomizeDlgText)\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"BannerLine\" Type=\"Line\" X=\"0\" Y=\"44\" Width=\"370\" Height=\"0\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"BottomLine\" Type=\"Line\" X=\"0\" Y=\"234\" Width=\"370\" Height=\"0\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Description\" Type=\"Text\" X=\"25\" Y=\"23\" Width=\"280\" Height=\"15\" Transparent=\"yes\" NoPrefix=\"yes\" Text=\"!(loc.CustomizeDlgDescription)\" />")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(4)
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(4 "<Control Id=\"Title\" Type=\"Text\" X=\"15\" Y=\"6\" Width=\"210\" Height=\"15\" Transparent=\"yes\" NoPrefix=\"yes\" Text=\"!(loc.CustomizeDlgTitle)\" />")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(3 "</Dialog>")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(2 "</UI>")
    __append_indented_lines_on_minpack_builder_customize_dialog_wxs(1 "</Fragment>")
    __append_blank_line_on_minpack_builder_customize_dialog_wxs(1)
    __end_minpack_builder_customize_dialog_wxs()
endfunction()
